TransportSystem/DeliveryProject/Controllers/DeliveryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Midterm.Models;
using DataLibrary.Models;
using DataLibrary;
using DeliveryProject.Models;

namespace DeliveryProject.Controllers
{
    public class DeliveryController : Controller
    {
        private DeliveryMarket dc;
        
        public DeliveryController()
        {
           dc = new DeliveryMarket();
        }
    
        public IActionResult Index()
        {
            return View();
        }

   
        public IActionResult NewOrder()
        {
           
            return View();
        }

        [HttpPost]
        public IActionResult NewOrder(Order o)
        {
            Write w = new Write();
            w.WriteToFile(o.ID,o.DistanceID,o.CategoryID,o.OrderedDate,o.Customer);
            return View();
        }


        public IActionResult Order()
        {
            var orders = dc.GetOrder();
            return View(orders);
        }

        public IActionResult Road()
        {
            var records = dc.GetRoad();
            ViewData["Message"] = "Your contact page.";

            return View(records);
        }

        public IActionResult Category()
        {
            var categories = dc.GetCategory();
            ViewData["Message"] = "Your contact page.";

            return View(categories);
        }

        public IActionResult Records()
        {
            var records = dc.GetRecord();
            ViewData["Message"] = "Your contact page.";

            return View(records);
        }

                
        //Отсортировать по цене 
        public IActionResult SortByPrice()
        {
            var sortedAmount = dc.SortedPrice();
            return View(sortedAmount);
        }

        public IActionResult GroupByName()
        {
            var group = dc.GroupedName();
            return View(group);
        }


        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TransportSystem/DeliveryProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  
    <title></title>
    <style>

        .new {

           background-color: red;
                   
        }
        .texts {
            width: 200px;
            padding-top: 15px;
            margin-left: 100px;
           
        }
        h4{
            margin-left:150px;
        
        }
        .operation{
            width: 50px;
            height: 30px;
            margin-left: 200px;
        }

        .button {
            margin-left: 180px;
            margin-top: 50px;
        }
    </style>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Midterm</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="new">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Delivery" asp-action="NewOrder">New Order</a></li>
                    <li><a asp-area="" asp-controller="Delivery" asp-action="Order">Orders</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reference<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Delivery" asp-action="Road">Roads</a></li>
                            <li><a asp-area="" asp-controller="Delivery" asp-action="Category">Category</a></li>
                        </ul>
                    </li> 
                   
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Records<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Delivery" asp-action="Records">Records</a></li>
                            <li><a asp-area="" asp-controller="Delivery" asp-action="SortByPrice">Sorted</a></li>
                            <li><a asp-area="" asp-controller="Delivery" asp-action="GroupByName">Grouped</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>